
package com.nhry.webservice.client.order;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import com.nhry.service.basic.dao.BranchEmpService;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2016-06-17T13:44:39.256+08:00
 * Generated source version: 3.0.5
 * 
 */
public final class OrderService_OrderService_Client {

    private static final QName SERVICE_NAME = new QName("http://dao.server.webservice.nhry.com/", "OrderServiceService");

    private OrderService_OrderService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
//        URL wsdlURL = OrderServiceService.WSDL_LOCATION;
//        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
//            File wsdlFile = new File(args[0]);
//            try {
//                if (wsdlFile.exists()) {
//                    wsdlURL = wsdlFile.toURI().toURL();
//                } else {
//                    wsdlURL = new URL(args[0]);
//                }
//            } catch (MalformedURLException e) {
//                e.printStackTrace();
//            }
//        }
//      
//        OrderServiceService ss = new OrderServiceService(wsdlURL, SERVICE_NAME);
//        OrderService port = ss.getOrderService();  
//        
//        {
//        System.out.println("Invoking getTreeCodeItemsByTypeCode...");
//        java.lang.String _getTreeCodeItemsByTypeCode_arg0 = "1001";
//        java.util.List<com.nhry.webservice.client.order.NhSysCodeItem> _getTreeCodeItemsByTypeCode__return = port.getTreeCodeItemsByTypeCode(_getTreeCodeItemsByTypeCode_arg0);
//        System.out.println("getTreeCodeItemsByTypeCode.result=" + _getTreeCodeItemsByTypeCode__return.size());
//
//
//        }
//
//        System.exit(0);
    	
    	
    	
    	String[] xmls = new String[]{ "classpath:beans/spring-context.xml","beans/classpath:dataSource.xml","classpath:beans/*-bean.xml"  };
        ApplicationContext context = new ClassPathXmlApplicationContext(xmls);
        OrderService service = (OrderService)context.getBean("orderClient");
        System.out.println(service.getTreeCodeItemsByTypeCode("1001").size());
    }

}
