package com.nhry.webservice.client.order;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2016-06-17T13:44:39.314+08:00
 * Generated source version: 3.0.5
 * 
 */
@WebService(targetNamespace = "http://dao.server.webservice.nhry.com/", name = "OrderService")
@XmlSeeAlso({ObjectFactory.class})
public interface OrderService {

    @WebMethod
    @RequestWrapper(localName = "getTreeCodeItemsByTypeCode", targetNamespace = "http://dao.server.webservice.nhry.com/", className = "com.nhry.webservice.client.order.GetTreeCodeItemsByTypeCode")
    @ResponseWrapper(localName = "getTreeCodeItemsByTypeCodeResponse", targetNamespace = "http://dao.server.webservice.nhry.com/", className = "com.nhry.webservice.client.order.GetTreeCodeItemsByTypeCodeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.nhry.webservice.client.order.NhSysCodeItem> getTreeCodeItemsByTypeCode(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
