package com.nhry.webservice.client.order;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2016-06-17T13:44:39.323+08:00
 * Generated source version: 3.0.5
 * 
 */
@WebServiceClient(name = "OrderServiceService", 
                  wsdlLocation = "http://127.0.0.1:8082/NhryService/ws/order/orderServicePort?wsdl",
                  targetNamespace = "http://dao.server.webservice.nhry.com/") 
public class OrderServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dao.server.webservice.nhry.com/", "OrderServiceService");
    public final static QName OrderService = new QName("http://dao.server.webservice.nhry.com/", "orderService");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8082/NhryService/ws/order/orderServicePort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrderServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8082/NhryService/ws/order/orderServicePort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrderServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns OrderService
     */
    @WebEndpoint(name = "orderService")
    public OrderService getOrderService() {
        return super.getPort(OrderService, OrderService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderService
     */
    @WebEndpoint(name = "orderService")
    public OrderService getOrderService(WebServiceFeature... features) {
        return super.getPort(OrderService, OrderService.class, features);
    }

}
